name: Generate Metrics
on:
  # push:
  #   branches: [main]
  schedule: 
    - cron: "0 0 */3 * *"
  workflow_dispatch: # enabled

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          #committer_token: ${{ secrets.GITHUB_TOKEN }}
          #committer_branch: metrics_output

          template: classic
          
          repositories_affiliations: ''
          #commits_authoring: nixinova@gmail.com, Nixinova@users.noreply.github.com, 42429413+Nixinova@users.noreply.github.com
          config_timezone: Europe/Athens

          base: header, activity, repositories  # header, activity, community, repositories, metadata
          plugins_errors_fatal: no

          plugin_lines: yes
          plugin_traffic: yes

          # plugin_followup: yes
          # plugin_followup_sections: repositories, user
          
          # plugin_discussions: yes

          plugin_languages: yes
          plugin_languages_details: percentage, lines
          plugin_languages_sections: recently-used
          # plugin_languages_colors: "less:#261f7a"
          # plugin_languages_aliases: "less:NovaSheets"
          plugin_languages_indepth: yes

          # plugin_gists: yes

          plugin_topics: yes
          plugin_topics_sort: stars
          plugin_topics_mode: mastered
          plugin_topics_limit: 0 # disable

          # plugin_isocalendar: yes
          # plugin_isocalendar_duration: full-year

          # plugin_activity: yes
          # plugin_activity_limit: 5
          # plugin_activity_timestamps: yes
          
          # plugin_achievements: yes
          # plugin_achievements_limit: 0