name: Test
on:
  push:
    branches: [main]
  schedule: 
    - cron: "0 0 * * *"
  workflow_dispatch: # enabled

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:

          token: ${{ secrets.METRICS_TOKEN }}
          #committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: metrics_output

          template: classic
          repositories_affiliations: ''
          config_timezone: Europe/Athens